module.exports = [
  { species: 'Jaguar', extinct: false, location: 'South America', lifeExpectancy: 12 },
  { species: 'Leatherback Turtle', extinct: false, location: 'Oceans', lifeExpectancy: 45 },
  { species: 'Lion', extinct: false, location: 'Africa', lifeExpectancy: 12 },
  { species: 'Manta Ray', extinct: false, location: 'Oceans', lifeExpectancy: 20 },
  { species: 'Mountain Gorilla', extinct: false, location: 'Africa', lifeExpectancy: 35 },
  { species: 'Narwhal', extinct: false, location: 'Arctic', lifeExpectancy: 50 },
  { species: 'Orangutan', extinct: false, location: 'Indonesia', lifeExpectancy: 45 },
  { species: 'Polar Bear', extinct: false, location: 'Arctic', lifeExpectancy: 25 },
  { species: 'Pygmy Hippopotamus', extinct: false, location: 'Africa', lifeExpectancy: 35 },
  { species: 'Red Panda', extinct: false, location: 'Himalayas', lifeExpectancy: 14 },
  { species: 'Saltwater Crocodile', extinct: false, location: 'Australia', lifeExpectancy: 70 },
  { species: 'Sea Otter', extinct: false, location: 'North America', lifeExpectancy: 20 },
  { species: 'Siberian Tiger', extinct: false, location: 'Russia', lifeExpectancy: 14 },
  { species: 'Snow Leopard', extinct: false, location: 'Central Asia', lifeExpectancy: 12 },
  { species: 'Sperm Whale', extinct: false, location: 'Oceans', lifeExpectancy: 70 },
  { species: 'Sumatran Rhino', extinct: true, location: 'Indonesia', lifeExpectancy: 35 },
  { species: 'Sun Bear', extinct: false, location: 'Southeast Asia', lifeExpectancy: 25 },
  { species: 'Thresher Shark', extinct: false, location: 'Oceans', lifeExpectancy: 22 },
  { species: 'Tiger Shark', extinct: false, location: 'Oceans', lifeExpectancy: 12 },
  { species: 'West Indian Manatee', extinct: false, location: 'Caribbean', lifeExpectancy: 40 },
  { species: 'White Rhinoceros', extinct: false, location: 'Africa', lifeExpectancy: 40 },
  { species: 'Whale Shark', extinct: false, location: 'Oceans', lifeExpectancy: 70 },
  { species: 'Wild Yak', extinct: false, location: 'Central Asia', lifeExpectancy: 20 },
  { species: 'Yellow-crested Cockatoo', extinct: true, location: 'Indonesia', lifeExpectancy: 40 },
];